### ISSUE TITLE
Create question not working

### ISSUE THREAD

**Issue by emilbowry** [tankh99/learnie-plugin#1]
When highlighting and clicking from command pallets create question, nothing happens. From the clip on readme, I expected a prompt but nothing happens.

https://github.com/user-attachments/assets/6cbb91cc-903d-416c-8210-d183d3968327

**Comment by tankh99** [comment]
Hey there @emilbowry, thanks for raising this issue. I believe the issue here is because you haven't converted the note into a Learnie-compatible note. Can you try using the `Learnie: Convert to Note` command first, then create the question?

**Comment by emilbowry** [comment]
Thanks that works!
